#!/usr/bin/env bash
#print divible numbers

for a in {1..100}
do
	if [[ $(( a%15 )) == 0 ]]
	then
		echo "FizzBuzz"
	elif [[ $(( a%3 )) == 0 ]]
	then
		echo "Fizz"
	elif [[ $(( a%5 )) == 0 ]]
	then
		echo "Buzz"
	else
		echo "$a"
	fi
done
