#!/usr/bin/env bash
#Print bad luck and good luck

name="Best School"

i=1
while [ $i -lt 11 ]
do
	if [ "$i" -eq 4 ]
	then
		echo "bad luck"
	elif [ "$i" -eq 8 ]
	then
		echo "good luck"
	else
		echo "$name"

	fi
	i=$(( i+1 ))
done
