#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 min


i=0
while [ "$i" -lt 13 ]
do
	echo "Hour: $i"
	minute=1
	while [ $minute -le 59 ]
	do
		echo "$minute"
		minute=$(( minute+1 ))
	done
	i=$(( i+1 ))
done
