#!/usr/bin/env bash
#Change the localhost

#copy files to test files
cp /etc/hosts ~/hosts.test

#change the values
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.test

#apply changes
cp -f ~/hosts.test /etc/hosts
